/**
 * Ambient type declarations for the `perry/system` module.
 *
 * The real `.d.ts` for `perry/system` is generated by `perry types` and
 * lands under `.perry/types/`. Until the user has run that command, we
 * keep a hand-written stub here so `tsc --noEmit` and IDE tooling work.
 *
 * The stub is intentionally narrow: it declares only the symbols the
 * project actually imports. If the real Perry API has more, the stub
 * doesn't need to grow.
 */
declare module "perry/system" {
    /** Current OS dark-mode setting. */
    export function isDarkMode(): boolean;

    /** Open a URL in the default handler (browser, mail, …). */
    export function openURL(url: string): void;

    /** Show a local notification. */
    export function notificationSend(title: string, body: string): void;

    /** True when the OS reports "reduce motion" / accessibility slow animations. */
    export function prefersReducedMotion(): boolean;
}
