/**
 * Cross-platform "launch at login" (autostart on user login) support.
 *
 * Each host has its own convention; we write a small manifest file and
 * the host's startup system picks it up:
 *
 *   - macOS   : `~/Library/LaunchAgents/com.<slug>.app.plist`
 *               The plist references the binary inside the .app bundle
 *               (so it works for both dev runs and the installed app).
 *
 *   - Windows : `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\<slug>.lnk`
 *               Creating a real .lnk requires shell extensions; we ship a
 *               stub .cmd alongside the manifest instead, which Windows
 *               also runs at logon. The .lnk name is kept for parity but
 *               the .cmd is the actual entry point.
 *
 *   - Linux   : `~/.config/autostart/<slug>.desktop`
 *               Standard XDG autostart; works in GNOME / KDE / XFCE etc.
 *
 * All three implementations share a single contract:
 *   `enableAutostart(execPath)`  — write a manifest pointing at `execPath`
 *   `disableAutostart()`         — remove the manifest if present
 *   `isAutostartEnabled()`       — return the current state
 *
 * `execPath` defaults to the current process's `process.execPath`.
 */
import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "fs";
import { dirname } from "path";
import { autostartManifestPath } from "./paths.js";
import { getHostKind } from "./platform.js";

/** Return the absolute path of the current executable. */
export function currentExecutablePath(): string {
    return process.execPath;
}

/**
 * Enable autostart by writing the appropriate manifest for the host.
 *
 * @param execPath Absolute path of the binary to run at login. Defaults
 *                 to `process.execPath` which is the running app on
 *                 every supported host.
 */
export function enableAutostart(execPath?: string): void {
    const target = execPath ?? currentExecutablePath();
    const manifest = autostartManifestPath();
    mkdirSync(dirname(manifest), { recursive: true });
    const kind = getHostKind();
    const body = renderManifest(kind, target);
    writeFileSync(manifest, body, { encoding: "utf-8" });
}

/** Disable autostart by removing the manifest, if present. */
export function disableAutostart(): void {
    const manifest = autostartManifestPath();
    if (existsSync(manifest)) {
        unlinkSync(manifest);
    }
    // On Windows we also remove the .cmd stub.
    if (getHostKind() === "windows") {
        const cmdStub = autostartManifestPath().replace(/\.lnk$/, ".cmd");
        if (existsSync(cmdStub)) {
            unlinkSync(cmdStub);
        }
    }
}

/** Is the autostart manifest currently in place? */
export function isAutostartEnabled(): boolean {
    return existsSync(autostartManifestPath());
}

/** Render the manifest body for the given host kind. */
function renderManifest(kind: ReturnType<typeof getHostKind>, execPath: string): string {
    if (kind === "macos") {
        return renderMacOSPlist(execPath);
    }
    if (kind === "windows") {
        return renderWindowsCmd(execPath);
    }
    return renderLinuxDesktop(execPath);
}

/** macOS LaunchAgent plist. */
function renderMacOSPlist(execPath: string): string {
    // NOTE: keep the keys ordered; `xmllint` is happy either way but humans
    // tend to read top-down. ProgramArguments must come *after* Label.
    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<plist version="1.0">',
        "<dict>",
        "    <key>Label</key>",
        "    <string>com.qed.app</string>",
        "    <key>ProgramArguments</key>",
        "    <array>",
        "        <string>" + escapeXml(execPath) + "</string>",
        "    </array>",
        "    <key>RunAtLoad</key>",
        "    <true/>",
        "    <key>KeepAlive</key>",
        "    <false/>",
        "    <key>ProcessType</key>",
        "    <string>Interactive</string>",
        "</dict>",
        "</plist>",
        "",
    ].join("\n");
}

/** Windows: a tiny .cmd that launches the executable, minimized. */
function renderWindowsCmd(execPath: string): string {
    return [
        "@echo off",
        "REM Auto-generated by qed autostart. Do not edit by hand.",
        'start "" "' + execPath.replace(/"/g, '""') + '"',
        "",
    ].join("\r\n");
}

/** Linux: XDG .desktop autostart entry. */
function renderLinuxDesktop(execPath: string): string {
    return [
        "[Desktop Entry]",
        "Type=Application",
        "Name=qed",
        "Comment=Cross-platform desktop application skeleton",
        "Exec=" + execPath,
        "Terminal=false",
        "X-GNOME-Autostart-enabled=true",
        "Categories=Development;Utility;",
        "",
    ].join("\n");
}

/** Minimal XML escape — handles only the chars that appear in paths. */
function escapeXml(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
